platform :ios, '7.0'

target 'WuliWebo' do

  pod 'ReactiveCocoa'
  pod "WeiboSDK"
  pod 'CocoaLumberjack'
  pod 'pop'
  pod 'IQKeyboardManager'
  pod "UIAlertView-Blocks", "~> 1.0"
  pod 'DTCoreText'
  pod 'SECoreTextView'
  pod 'JTSImageViewController'
  pod 'RKNotificationHub'
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
  pod 'MWPhotoBrowser'
end
